### PR TITLE
initial zuul support

### PR DESCRIPTION
**Pull request by fredericlepied**
Depends-on: https://github.com/wazo-platform/sf-jobs/pull/37

### CODE REVIEW

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Review by tranchitella — APPROVED** [review]

**Comment by fredericlepied** [comment]
recheck

**Pull request merged**
